server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: root
    url: jdbc:postgresql://localhost:5432/kol
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: akshay.a@glocalmind.com
    password: qgdrjniravazukhl
    port: 587
    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          
    protocol: smtp
    test-connection: false